packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/adapters/*'
  - 'tools'
minimumReleaseAgeExclude:
  - '@nx/devkit@23.2.0'
  - '@nx/js@23.2.0'
  - '@nx/nx-darwin-arm64@23.2.0'
  - '@nx/nx-darwin-x64@23.2.0'
  - '@nx/nx-freebsd-x64@23.2.0'
  - '@nx/nx-linux-arm-gnueabihf@23.2.0'
  - '@nx/nx-linux-arm64-gnu@23.2.0'
  - '@nx/nx-linux-arm64-musl@23.2.0'
  - '@nx/nx-linux-x64-gnu@23.2.0'
  - '@nx/nx-linux-x64-musl@23.2.0'
  - '@nx/nx-win32-arm64-msvc@23.2.0'
  - '@nx/nx-win32-x64-msvc@23.2.0'
  - '@nx/workspace@23.2.0'
  - 'nx@23.2.0'
  - '@nx/eslint@23.2.0'
  - '@nx/react@23.2.0'
  - '@nx/vite@23.2.0'
  - '@nx/vitest@23.2.0'
  - '@nx/web@23.2.0'
  - '@nx/eslint-plugin@23.2.0'
allowBuilds:
  nx: true
  '@swc/core': true
  esbuild: true
  msw: false
